version: '3.8'
services:   

  test-app-alpine:
    image: "${TEST-APP-ALPINE}"
    build:
      context: .
      dockerfile: Dockerfile-alpine

  test-app-centos:
    image: "${TEST-APP-CENTOS}"
    build:
      context: .
      dockerfile: Dockerfile-centos