version: '3.8'
services:   

  test-app-alpine:
    image: "${TEST_APP_ALPINE_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile-alpine

  test-app-centos:
    image: "${TEST_APP_CENTOS_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile-centos