version: '3.8'
services:   

  test-app-alpine:
    image: test-app:alpine-test
    build:
      context: .
      dockerfile: Dockerfile-alpine

  test-app-centos:
    image: test-app:alpine-test
    build:
      context: .
      dockerfile: Dockerfile-centos